#In app:
#from daily_values import daily_values as dv --> specify value you want.
# dv.get('keyword') - same code as before

daily_values = {
    "Added sugars": {"value": 50, "unit": "g"},
    "Biotin": {"value": 30, "unit": "mcg"},
    "Calcium": {"value": 1300, "unit": "mg"},
    "Chloride": {"value": 2300, "unit": "mg"},
    "Choline": {"value": 550, "unit": "mg"},
    "Cholesterol": {"value": 300, "unit": "mg"},
    "Chromium": {"value": 35, "unit": "mcg"},
    "Copper": {"value": 0.9, "unit": "mg"},
    "Dietary Fiber": {"value": 28, "unit": "g"},
    "Fat": {"value": 78, "unit": "g"},
    "Folate/Folic Acid": {"value": 400, "unit": "mcg DFE"},
    "Iodine": {"value": 150, "unit": "mcg"},
    "Iron": {"value": 18, "unit": "mg"},
    "Magnesium": {"value": 420, "unit": "mg"},
    "Manganese": {"value": 2.3, "unit": "mg"},
    "Molybdenum": {"value": 45, "unit": "mcg"},
    "Niacin": {"value": 16, "unit": "mg NE"},
    "Pantothenic Acid": {"value": 5, "unit": "mg"},
    "Phosphorus": {"value": 1250, "unit": "mg"},
    "Potassium": {"value": 4700, "unit": "mg"},
    "Protein": {"value": 50, "unit": "g"},
    "Riboflavin": {"value": 1.3, "unit": "mg"},
    "Saturated fat": {"value": 20, "unit": "g"},
    "Selenium": {"value": 55, "unit": "mcg"},
    "Sodium": {"value": 2300, "unit": "mg"},
    "Thiamin": {"value": 1.2, "unit": "mg"},
    "Total carbohydrate": {"value": 275, "unit": "g"},
    "Vitamin A": {"value": 900, "unit": "mcg RAE"},
    "Vitamin B6": {"value": 1.7, "unit": "mg"},
    "Vitamin B12": {"value": 2.4, "unit": "mcg"},
    "Vitamin C": {"value": 90, "unit": "mg"},
    "Vitamin D": {"value": 20, "unit": "mcg"},
    "Vitamin E": {"value": 15, "unit": "mg alpha-tocopherol"},
    "Vitamin K": {"value": 120, "unit": "mcg"},
    "Zinc": {"value": 11, "unit": "mg"}
}

dailyvalues_blank = {
    "Added sugars": {"value": 0, "unit": "g"},
    "Biotin": {"value": 0, "unit": "mcg"},
    "Calcium": {"value": 0, "unit": "mg"},
    "Chloride": {"value": 0, "unit": "mg"},
    "Choline": {"value": 0, "unit": "mg"},
    "Cholesterol": {"value": 0, "unit": "mg"},
    "Chromium": {"value": 0, "unit": "mcg"},
    "Copper": {"value": 0, "unit": "mg"},
    "Dietary Fiber": {"value": 0, "unit": "g"},
    "Fat": {"value": 0, "unit": "g"},
    "Folate/Folic Acid": {"value": 0, "unit": "mcg DFE"},
    "Iodine": {"value": 0, "unit": "mcg"},
    "Iron": {"value": 0, "unit": "mg"},
    "Magnesium": {"value": 0, "unit": "mg"},
    "Manganese": {"value": 0, "unit": "mg"},
    "Molybdenum": {"value": 0, "unit": "mcg"},
    "Niacin": {"value": 0, "unit": "mg NE"},
    "Pantothenic Acid": {"value": 0, "unit": "mg"},
    "Phosphorus": {"value": 0, "unit": "mg"},
    "Potassium": {"value": 0, "unit": "mg"},
    "Protein": {"value": 0, "unit": "g"},
    "Riboflavin": {"value": 0, "unit": "mg"},
    "Saturated fat": {"value": 0, "unit": "g"},
    "Selenium": {"value": 0, "unit": "mcg"},
    "Sodium": {"value": 0, "unit": "mg"},
    "Thiamin": {"value": 0, "unit": "mg"},
    "Total carbohydrate": {"value": 0, "unit": "g"},
    "Vitamin A": {"value": 0, "unit": "mcg RAE"},
    "Vitamin B6": {"value": 0, "unit": "mg"},
    "Vitamin B12": {"value": 0, "unit": "mcg"},
    "Vitamin C": {"value": 0, "unit": "mg"},
    "Vitamin D": {"value": 0, "unit": "mcg"},
    "Vitamin E": {"value": 0, "unit": "mg alpha-tocopherol"},
    "Vitamin K": {"value": 0, "unit": "mcg"},
    "Zinc": {"value": 0, "unit": "mg"}
}